# Generated by Django 5.1.6 on 2025-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_alter_patient_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
