# Generated by Django 5.1.6 on 2025-03-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users_app.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users_app.patient"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescribed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users_app.doctor"
            ),
        ),
    ]
