# Generated by Django 5.1.6 on 2025-03-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
