# Generated by Django 5.1.6 on 2025-03-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_appointment_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="payment_status",
        ),
    ]
