# Generated by Django 5.1.6 on 2025-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_remove_appointment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
